### ISSUE TITLE
Babel and Flow config should not be a part of app code

### ISSUE THREAD

**Issue by ericvicenti** [react-community/create-react-native-app#109]
Should we consider hiding the babel and flow configs for each CRNA, and managing them as a part of `react-native-scripts`? This would bring CRNA in line with the behavior of CRA.

**Comment by dikaiosune** [comment]
I think that'd be fantastic! I would love to do the same for watchman as well. I think this would require several things to happen:

1. Pass the babel configuration to the RN packager (we need the expo preset as a layer on top of the RN preset to handle local asset requires)
2. Figure out some way for the flow config to be extendable by the user -- we'd want to use the one from react-native-scripts and merge it with any ignores or other options specified by someone who naively runs `flow init`. We don't want to remove the flow config entirely and leave the user to their own devices (CRA gets away with this because all of its deps are much better behaved about adding noise to the flow results).
3. Would need to programmatically tell watchman about the empty config rather than relying on its directory-based config discovery.
4. Make sure that all of these files get written to the project directory on eject.
