### ISSUE TITLE
Rename file error

### ISSUE THREAD

**Issue by kaueDM** [react-community/create-react-native-app#158]
## Description

App crashes when i change the name of any file

## Expected Behavior

Packager check again all files looking for new ones or renamed files

## Observed Behavior

```
9:58:06 PM: (node:18655) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4235): Error: ENOENT: no such file or directory, open '/home/kauedm/Projects/Repositories/rh-temp/code/src/components/_applicationRouter.js'
```

## Environment

* `npm ls react-native-scripts`: 0.0.27
* `npm ls react-native`: 0.42.3
* `npm ls expo`: 15.1.3
* `node -v`: 7.8.0
* `npm -v`: 4.2.0
* `yarn --version`: ----
* `watchman version`: 4.7.0

Operating system: Ubuntu 16.10
Phone & version: Moto G4 Plus - Android 7.0

**Comment by dikaiosune** [comment]
Hi! Thanks for the report!

This is very concerning. Can you upload a working example somewhere with exact instructions to reproduce the error you're seeing?

**Comment by kaueDM** [comment]
@dikaiosune I just created a new project and inside it a new file, then started the packager.
While the packager is running, i renamed from `myNewFile.js` to `anotherName.js`. Doing this my app crashed.
If i stop my packager and start it again, everything is fine. Is really necessary an example?

**Comment by dikaiosune** [comment]
Did you import/require the file that you renamed?

**Comment by kaueDM** [comment]
Imported.
When i renamed my file, i updated the import too, matching the new file name.

**Comment by dikaiosune** [comment]
In attempting to reproduce, these are the steps I took. Please let me know how they differ from what you tried. If they match what you tried, let me know so that I can investigate potential differences in our development environments.

1. Created a fresh CRNA project (`create-react-native-app testrename`)
2. Started the packager (`cd testrename && yarn start`)
3. Loaded the app in the Expo client (scanned QR code, observed that welcome text displayed)
4. Created a new file with an empty module export called `lol.js` (contents: `module.exports = {}`)
5. Added `import lol from './lol';` to App.js, underneath the other imports (line 4 in the starter project)
6. Renamed `lol.js` to `lol2.js`, observed a packager syntax error due to a missing module
7. Changed the import to `import lol from './lol2';`, observed that the app reloaded without a syntax error
8. Changed the import to `import lol from './lol';`, observed syntax error again
9. Renamed `lol2.js` to `lol.js`, observed that the app reloaded successfully.

None of this required restarting the packager on my machine, and it would be really helpful for me if you could provide me with an example and steps you took that cause the issue on your machine.

**Comment by kaueDM** [comment]
Same steps. The only difference is `lol.js` content. I have this:
```
import React, { Component } from 'react';
import { Text, View } from 'react-native';

export default class lol extends Component {
    render() {
        return (
            <View>
                <Text>lol here</Text>
            </View>
        );
    }
}
```

When i rename my file, i change my class name too (to `lol2`), changing my import to
```
import lol2 from './lol2'
```
After this rename, i got the error related above.

**Comment by dikaiosune** [comment]
Cool -- that's very helpful, thank you. I'm able to reproduce that now, crazy! From tinkering, it looks like

```js
import React, { Component } from 'react';
import { Text, View } from 'react-native';

export default class lol extends Component {
    render() {
        return (
            <View>
                <Text>lol here</Text>
            </View>
        );
    }
}
```

requires the packager to be restarted, but

```js
import React, { Component } from "react";
import { Text, View } from "react-native";

export default class lol extends Component {
  render() {
    return (
      <View/>
    );
  }
}
```

does not. Can you confirm that it's the Text element which breaks live reloading on your machine?

**Comment by dikaiosune** [comment]
Also, to confirm, the issue here is that you can't reload your app **even by pressing the "Reload" button on the red box** or by pressing Cmd+R if you're in a simulator?

**Comment by kaueDM** [comment]
Yes, is the Text element the problem here. I tried with `<View />` and it worked.

Using the `Text` tag, if i press **RELOAD** in my phone, the error persists. Only work if i restart my packager. Can't help you about simulators, don't have any installed.

**Comment by dikaiosune** [comment]
Hm, OK. I just tried a few more times to reproduce and wasn't able to. I'll have to think about other factors that may be involved here.
