### ISSUE TITLE
Is the detach tool using the right version of react-native?

### ISSUE THREAD

**Issue by pbassut** [react-community/create-react-native-app#165]
Could you take a look at this issue?
https://github.com/invertase/react-native-firebase/issues/52#event-1044355308

**Comment by brentvatne** [comment]
Gradle configuration is the same between a new react-native project via `react-native init` to create a new project or `yarn detach` in a CRNA.

See diff of the resulting build.gradle files here:
https://www.diffchecker.com/uBh7jc6w

There seems to be some issue with your native configuration independent of what eject to ExpoKit does. Unfortunately these types of issues will arise when you eject because you now need to understand how the Android build system works.

cc @jesseruder in case he has some insight

**Comment by jesseruder** [comment]
Expo doesn't change anything in `LifecycleEventListener` or `ActivityEventListener`. Either there's a bug in the library, or it's targeting a different version of React Native.
