### ISSUE TITLE
Any plans to native module linking?

### ISSUE THREAD

**Issue by THPubs** [react-community/create-react-native-app#175]
Hi, will you be implementing `react-native link` support in the future?

**Comment by dikaiosune** [comment]
Due to the nature of loading your project in the Expo client, I don't expect this to ever be possible. You can use `react-native link` after ejecting, or if you create the project with `react-native init`.

Broadly, my hope is that the Expo client will eventually be able to cover most needs one might have for native modules, and that's true for many apps today.

**Comment by yash2code** [comment]
@dikaiosune  why it will be never possible 😢

**Comment by itanhduy** [comment]
Expo will never to be a good choice for developing RN app. It has been lacking lots of modules.
If Expo can resolve this problem. It will be the best solution for working with RN app.

**Comment by ide** [comment]
The code signing protections of the platforms prevent dynamically shipping native code. In addition, even if you loaded a signed dylib, both the App Store and Google Play requirements don’t allow this.

If you want to use custom native modules with Expo, you can detach and use Xcode/Android Studio along with most Expo APIs.
