### ISSUE TITLE
yarn run eject with Expo SDK

### ISSUE THREAD

**Issue by kavathiyamahesh** [react-community/create-react-native-app#192]
Hello Team,

I created project using 'create-react-native-app my-project' , I got success and I am able to run project via Expo, Thank you Expo.. We love you.

Now I start develop app in between I need to change something in Android folder like : App name and add app icon. But for this we need to Eject app 'yarn run eject' by this command.

I used this and now i am able to change App name and App icon, but how i can start again with Expo.
because when I type command 'yarn start' It's giving me error like :

yarn start v0.22.0
error Command "start" not found.

Please check how I eject expo :

**How would you like to eject from create-react-native-app?** 
ExpoKit: I'll create or log in with an Expo account to use React Native a An Expo account is required to proceed.

 **How would you like to authenticate? Log in with an existing Expo account**
Username/Email Address: 'my email'
Password: ********

Successfully logged in as kavathiyamahesh!

**You'll need to specify an Android package name. It must be unique on the Play Store if you want to
publish it there. See this StackOverflow question for more information:
What would you like your Android package name to be?** 'my package name'
Validating project manifest...
**Android project:** MyExpoTrial

**Successfully set up ExpoKit!
Ejected successfully!**

Let me know if there is any way to change code in android code and again I able to use Expo.

Thank you

**Comment by brentvatne** [comment]
hello! once you eject you cannot bring your project back in to expo. expo provides a shared native runtime that lets you just build your app in JS, as soon as you make native changes outside of our runtime then you need to build your own binaries :(

**Comment by rishii95** [comment]
Hi! Since you have ejected using ExpoKit option,you surely can use expo but not via npm start.
You will have to download Expo XDE and run project from there and get your QR code so that you can scan it from your Expo App in phone.

For further info https://www.google.co.in/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjCn9br_Z_XAhUJ5iYKHbNVCvUQFggoMAA&url=https%3A%2F%2Fdocs.expo.io%2Fversions%2Flatest%2Fintroduction%2Finstallation.html&usg=AOvVaw2al_oJo65EuqE1-XUNdyRY
