### ISSUE TITLE
Fix short cd output

### ISSUE THREAD

**Issue by dikaiosune** [react-community/create-react-native-app#24]
I broke the shortened `cd your-project` output at some point recently. Need to fix.

**Comment by usama54321** [comment]
Hi,

I just went through the code, and the culprit seems to be the following [line](https://github.com/react-community/create-react-native-app/blob/master/create-react-native-app/src/index.js#L65) in index.js (create-react-native-scripts)

`process.chdir(root); `

The current directory of the user is lost on execution of this line, which in turns to failure of [this](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/src/scripts/init.js#L114) line because the cwd is now the new project's root directory
`path.resolve(appName) === appPath`

Furthermore, i went through the init.js history and you initially had the following check instead of the above check, which made more sense
`path.join(process.cwd(),appName) === appPath`

but even this would not work as the child process's cwd is inherited from index.js, where it has already been changed to the project root.

I could make a quick fix by storing the cwd in a constant and passing it as the cwd of the spawned child for init.js, and send in a pull request

**Comment by dikaiosune** [comment]
Resolved in #44 -- thanks again @usama54321!
