### ISSUE TITLE
Very slow, Creating project takes almost half hour

### ISSUE THREAD

**Issue by dalisoft** [react-community/create-react-native-app#260]
I am new to React Native. Was come from tabris.js (still use). While i am installed dependecy and also did workaround for #258, download manual and (before did this always gived error):
```bash
$ npm install -g ngrok.tar.gz
```
but when i called `create-react-native-app MyApp`, tooks 30-35minutes.

Why soo slow, there workaround for it?

EDIT:
Running app on *Expo* also takes almost 10minutes or bit more

**Comment by brentvatne** [comment]
what are the specifications of your computer?

ngrok takes a long time to download, which would be part of it, but the rest is pretty standard stuff

**Comment by dalisoft** [comment]
I have already ngrok globally and cached.
windows 7 32bit dual core intel acer aspire 5610z. 11year old laptop

**Comment by brentvatne** [comment]
hey @dalisoft, wow 11 years old, incredible that it has lasted this long!

unfortunately running react-native tooling uses a decent amount of memory and requires a more up-to-date processor. for example, babel does a lot of work with react-native because all of the libraries ship in their raw (not-yet-transpiled) form, and so the react-native packager has to transpile everything inside of node_modules in addition to your app.

also, expo / create-react-native-app doesn't officially support windows 7 (neither does microsoft). i wish that we could support everybody that wants to use it, but we just don't have the resources.

if you'd like to give react-native a try on your machine, i'd recommend checking out https://snack.expo.io/ -- this will allow you to play with react-native in your browser and run it directly on your phone.

best of luck and thanks for checking out the project!

**Comment by dalisoft** [comment]
Thanks for reply. Maybe when youre using rollup with buble helps with performance, using npm does things faster than yarn. Really does performance improvements.

**Comment by dalisoft** [comment]
Win10 you recommend?

**Comment by brentvatne** [comment]
windows 10 would be a good choice! i think the main limitation here is hardware

**Comment by dalisoft** [comment]
Yea. Thanks

**Comment by guambejr** [comment]
Hi. I'm facing the same problem.
Mine it's taking hours (more than 12 hours).
I'm running on Arch Linux, node v8.2.1, npm 4.6.1.

Any help will greatly appreciated!

**Comment by dalisoft** [comment]
I ended up using Tabris.js, also built own structure on Tabris.js, look at [here](https://github.com/dalisoft/tez-native)

**Comment by Rumpz** [comment]
Hey there, just some feedback about this issue.
I'm having the same issue regarding react-create-app since i updated from node v-6 to node v-8.

I changed back my PATH variable to node v-6 and it runs normally.
So i suppose it as something to do with Version 8 of node or some kind of configuration between the two.

As a work around changing path variable on node version for the app creation seems to work !

**Comment by adithraghavs** [comment]
I've got the same issue too! It takes sooo long. I am on a Windows 10.

**Comment by omokehinde** [comment]
I am having the same issue. I have a windows 11 machine with Node 20.
