### ISSUE TITLE
App is using 172.16.123.1 as the IP address, which isn't on the network I'm connected to.

### ISSUE THREAD

**Issue by Haegin** [react-community/create-react-native-app#264]
## Description

When I run `yarn start` Expo starts running my app on 172.16.123.1:19001, which isn't the IP I'm using on the only network I'm connected to. Because of this I can't connect with my device.

## Expected Behaviour

I ran `yarn start` and was expecting it to start my app on my local machine, listening on the my network interface so I can connect from my phone.

## Observed Behavior

It started on 172.16.123.1:19001 which isn't the IP of my machine on the only network I'm connected to.
![image](https://user-images.githubusercontent.com/124099/27298983-bcdade94-54f8-11e7-8183-57e1bfff87b1.png)

My IP address is 172.46.0.206 and I'm not connected to any VPN, nor do I have Docker or any virtualisation software running that may create a dummy network adapter.

![image](https://user-images.githubusercontent.com/124099/27299032-eb345b94-54f8-11e7-991f-8ada36ddf980.png)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
```
grimoire@0.1.0 /Users/harry/dev/haegin/grimoire/grimoire
└── react-native-scripts@0.0.31 
```
* `npm ls react-native`:
```
grimoire@0.1.0 /Users/harry/dev/haegin/grimoire/grimoire
└── react-native@0.44.3 
```
* `npm ls expo`:
```
grimoire@0.1.0 /Users/harry/dev/haegin/grimoire/grimoire
└── expo@17.0.0 
```
* `node -v`: v8.1.0
* `npm -v`:5.0.3
* `yarn --version`: 0.19.1
* `watchman version`:4.7.0

Also specify:

1. Operating system:
![image](https://user-images.githubusercontent.com/124099/27299142-50879498-54f9-11e7-91a3-2ef657976555.png)

2. Phone/emulator/simulator & version:
OnePlus 3 but I can't connect it because of this bug.

## Reproducible Demo

`create-react-native-app grimoire`
`cd grimoire`
`yarn start`

**Comment by brentvatne** [comment]
hello! we use [node-ip](https://github.com/indutny/node-ip) `ip.address()`, which in turn calls node's [os.networkInterfaces()](https://nodejs.org/api/os.html#os_os_networkinterfaces) and then picks the first network interface. docker or hardware interfaces can sometimes cause problems with this, i'm not sure how the ordering of these is determined by the operating system. open to ideas for heuristics we can use, i'm not sure how we can pick from several network interfaces and know which one you'd like to use. so, it's easiest for you to configure the ip address that works if you have multiple network interfaces, and for that we expose [REACT_NATIVE_PACKAGER_HOSTNAME](https://github.com/react-community/create-react-native-app/blob/d01ddabb634532200629c6d17f920eb856fa6416/react-native-scripts/template/README.md#configuring-packager-ip-address)

**Comment by piotr-cz** [comment]
In my case the problem is that I'm running vagrant on VirtualBox which is creating two additional Ethernet adapters which are listed before physical Wireless adapter and so picked by the start script.

I think this can be fixed either by
- configuration option in package.json to either hardcode physical adapter IP or **subnet mask**
- manual config in Expo App

**Comment by AdamPD** [comment]
Why not rather than specify an IP address in the env variables, specify a network interface (or MAC address or other identifier)?

I have the common situation that when I take my laptop to different locations, I have to constantly reconfigure this IP address for my local wifi.

**Comment by piotr-cz** [comment]
As expo [recommends using Geanymotion](https://docs.expo.io/versions/v18.0.0/guides/genymotion.html) for emulation which is running on VirtualBox, this issue will probably come up more often

**Comment by brentvatne** [comment]
if you're having a trouble with this please consider sending a PR to help us improve it. I personally have never encountered this issue and cannot empathize well with it because I can't even re-create it. alternatively, you can use `exp` (http://github.com/expo/exp) or `xde` (https://github.com/expo/xde) to open your project -- they will automatically create a tunnel using `ngrok`, which lets you just forget about any of these issues.

**Comment by taylorren** [comment]
I have the same issue here. The awkward (mine is 192.168.56.1:19000) is the first virtual network that I have to use with my Vagrant. I also don't know how to rearrange it.

**Comment by pdalfarr** [comment]
Same issue here....

**Comment by pdalfarr** [comment]
@brentvatne Can you please explain a bit the 'ngrok' based solution?
Thanks.

**Comment by itsAmr** [comment]
Take a look at this solution, may be helpful: https://github.com/react-community/create-react-native-app/issues/60#issuecomment-317104728

**Comment by MrLuje** [comment]
Or [this one](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md#configuring-packager-ip-address), which uses env variables

**Comment by bennycode** [comment]
On my machine Expo also picks a 172.x.x.x IP address (from my Hyper-V Virtual Ethernet Adapter) instead of my preferred 192.x.x.x IP address. Thus the generated QR links to an unreachable IP. Is there a command line flag that I can use to change that behaviour?

Screenshot:

![image](https://github.com/expo/create-react-native-app/assets/469989/7b4fe1c2-f02f-41a5-a0e3-4a9fc4ebb31f)
