### ISSUE TITLE
Stuck at Starting : Intent  { ....MainActivity }

### ISSUE THREAD

**Issue by yash2code** [react-community/create-react-native-app#303]
I recently ejected my CRNA project to expokit.

expo sdk is v 18.0.3 

Trying running on device using `react-native run-android` command

stuck at : 

![stuck](https://user-images.githubusercontent.com/20199248/28090890-8d35ee1c-66ab-11e7-97b4-7c20e2953ade.PNG)

On mobile device : 
![whatsapp image 2017-07-12 at 02 41 38](https://user-images.githubusercontent.com/20199248/28090946-c2ff950c-66ab-11e7-80d9-6a68e6c0cc6b.jpeg)

**Comment by flyher** [comment]
1 .run android 6
```shell
react-native run-android
```
it show the same errors

![111](https://user-images.githubusercontent.com/5570324/28238250-118d68c4-6982-11e7-854f-bfdcbfe73cd4.png)
2.Then i start the server in 8091
```shell
>react-native start --port=8091
>adb reverse tcp:8091 tcp:8091
```

reload the screen in my android phone , the problem solved.


i think the problem is the server haven't connected with your client.mybe you can try to start in the other  port.

**Comment by brentvatne** [comment]
> Trying running on device using react-native run-android command

as per readme, please use `npm run android`. 

interop with the react-native-cli is a known issue: https://github.com/react-community/create-react-native-app/issues/294 :)

**Comment by jpdenford** [comment]
I had a similar problem, this issue came up when searching so I'll add my two cents for anyone who might have the same issue.

I accidentally added another build *Flavor* to my `app` module called "universal". I was able to build inside Android Studio but not from the command line (by running `react-native run-android`) as it looked for the build variant `debug` not `universalDebug`.

**To fix** I removed the  "universal" flavor (leaving only the `defaultConfig`) from my `app` module (in the Project Structure menu of Android Studio).

**Comment by aditodkar** [comment]
I am facing same problem can someone please help me. How can I fix it ?

![screenshot_6](https://user-images.githubusercontent.com/16613832/45824617-096b0300-bd0e-11e8-8a70-22b9fc1c33b6.png)

**Comment by Gopal-Avegen** [comment]
Problem with me was metro bundler port used for many process at a time
1) Looked for working all the processes at that port by command `lsof -i :$PORT` in my case port was 8081
2) Killed all process at that port by  `kill -9 $(lsof -ti :$PORT)`

**Comment by govind-appnox** [comment]
@Gopal-Avegen, please check the targetSdkVersion in your build.gradle file, I was facing the same issue, but fixed it by lowering the targetSdkVersion or upgrading the React native version. It's a compatibility issue
