### ISSUE TITLE
Unable to install stable version of react

### ISSUE THREAD

**Issue by Pyrolistical** [react-community/create-react-native-app#306]
## Description

Currently `create-react-native-app@0.0.6` installs `react-native@0.45.x` and `react@16.0.0-alpha.12`

I want to be able to choose a stable version. I tried manually reverting back to `react-native@0.42.x` but I got a bunch of errors. I'm sure its possible, but the point is its not easy right now.

## Expected Behavior

Non alpha version of create-react-native-app should create a project that does not depend on alpha software

## Observed Behavior

`create-react-native-app@0.0.6` installs `react@16.0.0-alpha.12`

**Comment by brentvatne** [comment]
<img width="705" alt="screen shot 2017-07-17 at 12 20 37 pm" src="https://user-images.githubusercontent.com/90494/28285639-5f844dea-6aea-11e7-9b30-eeee8c4c91a7.png">

https://github.com/facebook/react-native/issues/14496

To verify, go to facebook.com, open your console and type `require('React').version`.

As for why you get `peerDependency` warnings, this is because according to npm, React 16.0.0-alpha.x is not >= 15.3.1 (I strongly believe that it should be -- [see this issue on the npm repository for more information](https://github.com/npm/npm/issues/8854)). Accordingly, we have to see these warnings every time we install something until we move off of React 16 alpha. Yarn is a bit more intelligent (imo) about this, and [will not show peerDependency errors in this situation](https://github.com/yarnpkg/yarn/pull/3361).

As for why you can't just install any arbitrary React Native version, this is because there are several dependencies that you need to change to make this work. You'll need to change the 1) react-native version, of course 2) react version 3) expo version ([see compat table](https://docs.expo.io/versions/v18.0.0/sdk/index.html#sdk-version)) 4) the expo `sdkVersion` in app.json.

Hope this helps!
