### ISSUE TITLE
Run app in production mode via npm?

### ISSUE THREAD

**Issue by Palisand** [react-community/create-react-native-app#321]
I know one can run a CRNA project in production mode via Expo's XDE or the exp CLI. Is this possible with `npm start` / the react native scripts?

**Comment by brentvatne** [comment]
hello! CRNA only lets you run in development mode right now, we'll add a way to toggle this with the interactive mode suggested in https://github.com/react-community/create-react-native-app/issues/126 -- for now you can install [exp](https://github.com/expo/exp) and use that instead of `npm start` -- `npm i -g exp` and then `exp start --no-dev`

**Comment by Palisand** [comment]
Closing in favor of #126

**Comment by rahamin1** [comment]
@fson Any update on the ability to run npm start in production mode?

**Comment by vjsingh** [comment]
@brentvatne  @Palisand 

Looking to run a CRNA app in production mode as well, to test performance issues. As suggested by the react docs (https://facebook.github.io/react-native/docs/performance)
