### ISSUE TITLE
Loading the app on expo by scanning QR code returns "Something went wrong. Network response timed out."

### ISSUE THREAD

**Issue by mellowstoked** [react-community/create-react-native-app#369]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`:
* `npm -v`:
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system:
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by terdia** [comment]
Description
Something went wrong. Network response timed out.

Expected Behavior
Show show the app in either iphone or android using expo (barcode scan)

npm ls react-native-scripts:
AwesomeProject@0.1.0 C:\Users\terry-vmi\Desktop\react\AwesomeProject
`-- react-native-scripts@1.2.1

npm ls react-native
AwesomeProject@0.1.0 C:\Users\terry-vmi\Desktop\react\AwesomeProject
`-- react-native@0.47.2

npm ls expo
AwesomeProject@0.1.0 C:\Users\terry-vmi\Desktop\react\AwesomeProject
`-- expo@20.0.2
  `-- UNMET PEER DEPENDENCY react@>=15.3.1

npm ERR! peer dep missing: react@>=15.3.1, required by lottie-react-native@1.1.1
npm ERR! peer dep missing: react@>=15.4.0, required by react-native-branch@2.0.0-beta.3
npm ERR! peer dep missing: react@>= 16.0.0, required by react-native-gesture-handler@1.0.0-alpha.17

node -v
v6.10.2

npm -v
3.10.10

yarn --version
0.24.6

watchman version
bash: watchman: command not found

Operating system:
Windows 10
iPad Air

**Comment by dikaiosune** [comment]
Hi! Please see the network troubleshooting section of the README, and make sure to complete the issue template when reporting bugs. Thanks!

**Comment by davelogear** [comment]
The words "network", "trouble", and "template" are not in the README... I guess I'll just open another issue as described in the README because this was the top Google result when searching for this error.

**Comment by dikaiosune** [comment]
@davelogear sorry for the confusion, I was referring to the README included with the template project: https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md

**Comment by adeniyi1007** [comment]
Got into this same issue.
