### ISSUE TITLE
Broken QR-Code

### ISSUE THREAD

**Issue by olegsugatov** [react-community/create-react-native-app#384]
After npm start default AwesomeProject i see unproportional QR-code, which i can't scan and start project on phone.

<img width="701" alt="2017-08-28 16 51 02" src="https://user-images.githubusercontent.com/26487259/29777464-c193d852-8c14-11e7-98e2-a779aa06ae96.png">

macOS Sierra 10.12.6
npm 5.3.0
node 8.4.0

**Comment by brentvatne** [comment]
hi there! I think the issue is with the font that you are using in the terminal. I don't think that much can be done about fonts that output these characters differently -- it looks like the box characters are taller than they are wide which is a problem with the font. we use the qrcode-terminal library for this: https://github.com/gtanner/qrcode-terminal/issues/21

**Comment by olegsugatov** [comment]
Thank you, Brent! 
Font Inconsolata works good with QR-code, but the problem was i used by default more spacing between lines in Terminal to improve readable.
