### ISSUE TITLE
peer dep missing: react@> 15.0.0 using create-react-native-app

### ISSUE THREAD

**Issue by julesmoretti** [react-community/create-react-native-app#420]
Please refer to: https://github.com/facebook/react-native/issues/16120

**Comment by julesmoretti** [comment]
@anyonehere... https://github.com/expo/expo/issues/726

**Comment by dikaiosune** [comment]
Hi! You're correct that peer dependency warnings will appear when installing certain dependencies in a react native project -- this is due to upstream RN's choice to depend on alpha/beta releases of React, which break yarn's and npm's semver calculations for peer dependencies. Unfortunately there's nothing we can do to resolve this until upstream react native supports a stable release of react 16 (I think this will happen in a month or two!!! exciting).

In most npm/yarn configurations, these should only be warnings, not errors. If they're preventing you from starting your project please check that the dependency you're adding relies on react as a peer dependency, not a direct dependency, and that you haven't configured your package manager to error on all warnings. It's an unfortunate reality of much of the JS ecosystem today that package manager warnings are pretty common.

**Comment by julesmoretti** [comment]
@dikaiosune i am not sure why you are so quick to close issues without a solution that I find helpful. Please hold off from just jumping the gun and making assumptions that you resolved the situation because you have not.

If you had taken the time to review me 2 other references those indicate and Error and not a waring therefore not allowing me to start react-native. So is waiting a month really a viable solution? I dont think so.

I will also answer you in the https://github.com/expo/expo/issues/726 issue which again was uncalled for.

**Comment by dikaiosune** [comment]
> In most npm/yarn configurations, these should only be warnings, not errors. If they're preventing you from starting your project please check that the dependency you're adding relies on react as a peer dependency, not a direct dependency, and that you haven't configured your package manager to error on all warnings.

**Comment by dikaiosune** [comment]
For future reference, I also replied in https://github.com/react-community/create-react-native-app/issues/425#issuecomment-334896572.
