### ISSUE TITLE
trying to run the app after ejecting "expokit" and getting this error Error running `xcrun simctl openurl booted expc...?

### ISSUE THREAD

**Issue by a-eid** [react-community/create-react-native-app#428]
## Description
After ejecting to expokit I can't run `exp ios`  to run app on simulator but I get the following error 

```
[exp] Making sure project is set up correctly...
/[exp] Warning: You are using npm version 5.3.0. There may be bugs in this version, use it at your own risk. We recommend version 4.6.1.
-[exp] Warning: Expo version in package.json does not match sdkVersion in manifest.
[exp]
[exp] If there is an issue running your project, please run `npm install` in /Users/aeid/developer/Billbored-Real-Frontend and restart.
[exp] Your project looks good!
[exp] Opening expc0af421430f54d00aad2c2f7aa438003://localhost:80 in iOS simulator
[exp] Error running `xcrun simctl openurl booted expc0af421430f54d00aad2c2f7aa438003://localhost:80`: An error was encountered processing the command (domain=NSOSStatusErrorDomain, code=-10814):
The operation couldn’t be completed. (OSStatus error -10814.)

[exp] Error running app. Have you installed the app already using Xcode? Since you are detached you must build manually. Error: Process exited with non-zero code: 194
```

**Comment by tcdavis** [comment]
Please resolve the warning in the logs, (the recommended downgrade to npm 4.6.1)

**Comment by a-eid** [comment]
@tcdavis that's interesting since when I do so npm hangs and doesn't install any dependancies. 
but I can try to resolve that . 
are you sure that this might be the problem ? 

thanks.

**Comment by a-eid** [comment]
```
[exp] Making sure project is set up correctly...
|[exp] Warning: 'react-native' peer depencency missing. Run `npm ls` in /Users/aeid/developer/Billbored-Real-Frontend to see full warning.
[exp] Warning: 'react-native-vector-icons' peer depencency missing. Run `npm ls` in /Users/aeid/developer/Billbored-Real-Frontend to see full warning.
[exp]
[exp] If there is an issue running your project, please run `npm install` in /Users/aeid/developer/Billbored-Real-Frontend and restart.
[exp] Your project looks good!
[exp] Opening expc0af421430f54d00aad2c2f7aa438003://localhost:80 in iOS simulator
[exp] Error running `xcrun simctl openurl booted expc0af421430f54d00aad2c2f7aa438003://localhost:80`: An error was encountered processing the command (domain=NSOSStatusErrorDomain, code=-10814):
The operation couldn’t be completed. (OSStatus error -10814.)

[exp] Error running app. Have you installed the app already using Xcode? Since you are detached you must build manually. Error: Process exited with non-zero code: 194
```

**Comment by tcdavis** [comment]
We've found npm 5 ends up causing more problems than it solves. Drop
node_modules and reinstall?

On Oct 9, 2017 6:26 PM, "Ahmed Eid" <notifications@github.com> wrote:

[exp] Making sure project is set up correctly...
|[exp] Warning: 'react-native' peer depencency missing. Run `npm ls`
in /Users/aeid/developer/Billbored-Real-Frontend to see full warning.
[exp] Warning: 'react-native-vector-icons' peer depencency missing.
Run `npm ls` in /Users/aeid/developer/Billbored-Real-Frontend to see
full warning.
[exp]
[exp] If there is an issue running your project, please run `npm
install` in /Users/aeid/developer/Billbored-Real-Frontend and restart.
[exp] Your project looks good!
[exp] Opening expc0af421430f54d00aad2c2f7aa438003://localhost:80 in
iOS simulator
[exp] Error running `xcrun simctl openurl booted
expc0af421430f54d00aad2c2f7aa438003://localhost:80`: An error was
encountered processing the command (domain=NSOSStatusErrorDomain,
code=-10814):
The operation couldn’t be completed. (OSStatus error -10814.)

[exp] Error running app. Have you installed the app already using
Xcode? Since you are detached you must build manually. Error: Process
exited with non-zero code: 194

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/react-community/create-react-native-app/issues/428#issuecomment-335332740>,
or mute the thread

**Comment by a-eid** [comment]
@tcdavis I did drop node_modules and reinstall still getting the following ourput ( with error ) : 

```
[exp] Making sure project is set up correctly...
-[exp] Warning: 'react-native' peer depencency missing. Run `npm ls` in /Users/aeid/developer/Billbored-Real-Frontend to see full warning.
[exp] Warning: 'react-native-vector-icons' peer depencency missing. Run `npm ls` in /Users/aeid/developer/Billbored-Real-Frontend to see full warning.
[exp]
[exp] If there is an issue running your project, please run `npm install` in /Users/aeid/developer/Billbored-Real-Frontend and restart.
[exp] Your project looks good!
[exp] Opening iOS simulator
[exp] Opening expc0af421430f54d00aad2c2f7aa438003://localhost:19000 in iOS simulator
[exp] Error running `xcrun simctl openurl booted expc0af421430f54d00aad2c2f7aa438003://localhost:19000`: An error was encountered processing the command (domain=NSOSStatusErrorDomain, code=-10814):
The operation couldn’t be completed. (OSStatus error -10814.)

[exp] Error running app. Have you installed the app already using Xcode? Since you are detached you must build manually. Error: Process exited with non-zero code: 194
```

**Comment by a-eid** [comment]
I'm also getting this error with android 

```
exp android
[exp] Making sure project is set up correctly...
/[exp] Warning: 'react-native' peer depencency missing. Run `npm ls` in /Users/aeid/developer/Billbored-Real-Frontend to see full warning.
[exp] Warning: 'react-native-vector-icons' peer depencency missing. Run `npm ls` in /Users/aeid/developer/Billbored-Real-Frontend to see full warning.
[exp]
[exp] If there is an issue running your project, please run `npm install` in /Users/aeid/developer/Billbored-Real-Frontend and restart.
[exp] Your project looks good!
[exp] Opening on Android device
[exp] Couldn't start project on Android: Error running adb: Error running app. Have you installed the app already using Android Studio? Since you are detached you must build manually. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=expc0af421430f54d00aad2c2f7aa438003://sh-74y.aeid.billbored-real-frontend.exp.direct:80 flg=0x10000000 }
```

**Comment by Tvtig** [comment]
I had the same issue, turns out i had a running instance of package manager whilst trying to run 'exp ios' after i closed that it worked.

**Comment by dikaiosune** [comment]
@a-eid can you open the iOS simulator manually?

**Comment by brentvatne** [comment]
closed for no response

**Comment by MEOWMEOW114** [comment]
I have the same issue and got the same error messages.
It could start the iOS simulator yet it cannot install/start any app.

**Comment by pierol** [comment]
I've the same issue, i created a project with `create-react-native-app` i've made a `yarn eject` a select with ExpoKit. Before ejecting i've installed the exp cli and also the XDE but if i made open it in ios simulator i get the error:

```
Error running `xcrun simctl openurl booted exp14eba1fed68148bd9eb08c305152dbc4://localhost:19000`: An error was encountered processing the command (domain=NSOSStatusErrorDomain, code=-10814):
The operation couldn’t be completed. (OSStatus error -10814.)
00:50:14
Error running app. Have you installed the app already using Xcode? Since you are detached you must build manually. Error: Process exited with non-zero code: 194
```

**Comment by JMW5** [comment]
Any solutions for this? Having the same error.

**Comment by pierol** [comment]
I solved the problem this way:

1. Open in Xcode the XCWORKSPACE project file under ios folder of your app.
2. Build and run the project in Xcode: this will install the app in iphone simulator
3. After that open the expo project in Expo XDE an run it
4. In Expo XDE make Device -> Open app in ios simulator

I supposed that the problem is because the Expo XDE is not able to create and install the app in ios simulator. Even more i notice that if you want hot reloading you always need to build and ren the project in Xcode before to run it in XDE.

**Comment by ide** [comment]
XDE is responsible just for invoking the React Native JS packager and sending the JS to your simulator or device. When you eject, you are responsible for everything else, such as building the iOS app with Xcode and installing it in the simulator.

Looking online, OSStatus error -10814 means `kLSApplicationNotFoundErr`. This hints that the target app is not installed on the simulator and you need to build it from Xcode. (The fix in the comment right above this one corroborates that.)

**Comment by lxbworld** [comment]
I meet this problem in Flutter project for IOS simulator, I solved it by closing the simulator and install app again...
