### ISSUE TITLE
Unable to open CRNA project on phone with remote URL

### ISSUE THREAD

**Issue by mukurpuri** [react-community/create-react-native-app#458]
Unlike Expo App (Tool), create-react-native-app does not create remote URL application to open up inside an Expo App.
The QR code produced by CRNA is unable to open app inside the mobile phone(with Expo app).
The Expo App(mobile) usually searches the project at the LAN network.

I created my project via CRNA and ran server(npm start), which then gave me a QR code. I scanned QR code via my expo mobile app.

Expectations:
My project running with a remote URL

Reality:
Expo app was unable to load exp://10.1.4.128.19000. Network response timed out.

I went through the settings.json & packager-info.json inside .expo folder in my project and didn't find the value of the key "urlRandomness", which is a unique url associated with my username with my expo account.

Also, CRNA never asked mine expo account etc.

Is CRNA only useful to view and develop a project on LAP or same network?

![image](https://user-images.githubusercontent.com/10636579/32038619-5f9639d0-ba48-11e7-92f3-67b3e0ffaa36.png)

**Comment by brentvatne** [comment]
hiya! correct, crna does not create a tunnel for you -- we left it out of crna because we didn't want to depend on an external service -- crna is meant to be service agnostic (technically you could even use something other than the expo app, if someone built something like that!). so you will need to be on the same network, connect your phone to your computer and use `adb reverse` (sorry plane wifi, you can google it and see how to use it) so you can refer to localhost as your computer from your phone :)
