### ISSUE TITLE
Why is eject operation is permanent?

### ISSUE THREAD

**Issue by glacjay** [react-community/create-react-native-app#510]
I've `eject`ed my create-react-native-app project, add back `expo` and `react-native-scripts` dependencies, and add a new npm command `expo-start`: `react-native-scripts start`, and it works again!

So I want to know: why the `eject` operation is permanent? Will there be problems of my way to add it back?

thx

**Comment by brentvatne** [comment]
you can add those back, sure! the problem is we have no way of automatically making your project work with expo/crna again. if you eject and add some native modules then decide you don't need them and expect some "uneject" to remove them for you (from js code), that won't happen. so perhaps the wording needs to be more clear in saying that there is no automated way to go back, but you can go back if you want to do the process manually.

**Comment by bcheidemann** [comment]
What's the process to uneject an app manually?

**Comment by brentvatne** [comment]
`rm -rf ios android`
