### ISSUE TITLE
How to get Debug in Chrome Developer tools?

### ISSUE THREAD

**Issue by antwerpenR** [react-community/create-react-native-app#55]
I am able to get my app up and running but how to get the Debug in Chrome Developer tools?
The only option that seems to work on the device is two finger touch and then "reload" but there seems to be no option any more for remote debug....?

**Comment by dikaiosune** [comment]
Hi! Are you on a physical phone? If so, you can shake the phone to access the RN dev menu.

Assuming that works, this needs to be added to the user guide.

**Comment by antwerpenR** [comment]
Hi - yes, thanks - indeed.  It would be good for you to put that on the splash screen, like it is for apps created by "react-native create...".

One more question.  How should I get the debugging to appear in Nuclide?   When I shake the phone it does open Chrome debugger in my browser but I would like to have that in Nuclide to have the full IDE experience.   Maybe I just need to dig a bit more in the docs but it also seems not entirely obvious...

**Comment by dikaiosune** [comment]
The "shake phone" documentation issue is resolved in 1ca22b8ab55bdae36ea8fd7ea270c7976203c928

I believe others have had issues getting debugging working in nuclide -- I've heard that it works in vscode, but I haven't repro'd. If this is an important issue for you please open a separate issue, since the title of this issue is resolved.
