### ISSUE TITLE
Again integrity failed while creating AwesomeProject 

### ISSUE THREAD

**Issue by hmzlam** [react-community/create-react-native-app#551]
## Description

the same as #356
any new user to react native will not be able to install framework following your startup instructions

## Expected Behavior

the same as #356

## Observed Behavior

```
the same as #356
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
acer@1.0.0 C:\Users\acer
`-- (empty
* `npm ls react-native`: 
same as above
* `npm ls expo`:
same as above
* `node -v`:
v8.9.4
* `npm -v`:
5.6.0
* `yarn --version`:
command not found
* `watchman version`:
command not found
Also specify:

1. Operating system:
windows 10 i3 64x
2. Phone/emulator/simulator & version:
nothing

**Comment by fson** [comment]
This is a common issue with npm (see https://github.com/npm/npm/issues/16861).

Can you try running `npm cache verify` and then retry?

**Comment by PHARMACIE1801** [comment]
C:\Users\acer>npm cache verify
Cache verified and compressed (~\AppData\Roaming\npm-cache\_cacache):
Content verified: 976 (24429810 bytes)
Content garbage-collected: 98 (44196683 bytes)
Index entries: 1490
Finished in 21.645s


--
  otherwise this i do it many times with a completely installation of a fresh new version of node, why there will be a cache?
--

**Comment by PHARMACIE1801** [comment]
problem persists
i really hope to have download  one big zip file and work with react native directly

**Comment by fson** [comment]
I'm sorry to hear you're having trouble with npm. At the moment Create React Native App doesn't bundle the dependencies and uses npm (or [Yarn](https://yarnpkg.com/) if you have it installed) to install them. CRNA takes this approach because for many users it works well, and because npm and Yarn cache packages, it can also be pretty fast after the first run.

At Expo we're also maintaining another command line tool named [exp](https://docs.expo.io/versions/latest/guides/exp-cli.html) that provides an experience that's in many ways quite similar to CRNA, but when you create a project, it currently downloads just one big file with everything, including the dependencies. Maybe you can give it a try?

**Comment by PHARMACIE1801** [comment]
Connecting to a high speed onternet solved the problem, 
it looks like npm is not designed to work with low speed conenxion
but i get now
*******************************************************************************
ERROR: npm 5 is not supported yet
*******************************************************************************

It looks like you're using npm 5 which was recently released.

Create React Native App doesn't work with npm 5 yet, unfortunately. We
recommend using npm 4 or yarn until some bugs are resolved.

You can follow the known issues with npm 5 at:
https://github.com/npm/npm/issues/16991

*******************************************************************************

**Comment by fson** [comment]
Many of the issues npm 5 had earlier have been fixed now, but there's still a few left. Once those have been fixed we can remove that warning.

In the meantime, maybe you can try [Yarn](https://yarnpkg.com/)?
