### ISSUE TITLE
There appears to be trouble with your network connection. Retrying...

### ISSUE THREAD

**Issue by liyanxi** [react-community/create-react-native-app#606]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`:
* `npm -v`:
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system:
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by YanYuanFE** [comment]
![image](https://user-images.githubusercontent.com/17774285/37751489-d28b6dae-2dcd-11e8-8456-270fc97b764d.png)
OS: ubuntu 16.04,
npm: v5.6.0
node: v9.9.0
create-react-native-app: v1.0.0

**Comment by brentvatne** [comment]
this might happen in china or on slow internet connections because we currently have a dependency on ngrok here, which is quite large, and it's also for no good reason because we don't use it. that said, it's a transitive dependency and it's installed from xdl and so we need to fix this upstream. sorry for the hassle, not much you can do now except install on a better internet connection and then for subsequent installs leverage the cache (automatic)
