### ISSUE TITLE
Connection issue after running npm start

### ISSUE THREAD

**Issue by davidlee1435** [react-community/create-react-native-app#63]
Hi all, after running npm start and scanning the QR code on the Expo app, I run into the following issue:

`"Error while loading: Could not connect to the server.." (code - 1004)`

I'm on Node version 7.7.2. The error persists even when I enter the address in the app's search bar. Thanks!

**Comment by dikaiosune** [comment]
Hi! Thanks for the report. Are your phone and computer on the same local network?

**Comment by davidlee1435** [comment]
@dikaiosune Yup! I also messaged the help channel on the expo-developer Slack channel and I was told that this issue was due to the particular Wifi router that I was using

**Comment by dikaiosune** [comment]
Interesting. You can try working around this by using your phone's WiFi hotspot if your data plan supports it. That is the easiest way to resolve networking issues currently.

**Comment by egor-laufer** [comment]
I had a very similar issue, although not exactly the same. For me, scanning the QR code resulted in connection timeout. Using phone's hotspot did not help, USB tethering did not work either. 

After some fiddling, I was able to fix the issue using combination of `adb reverse tcp:8081 tcp:8081` and the following lines in `.expo/settings.json` (only hostType should be crucial):

```
{
  "hostType": "localhost",
  "lanType": "ip",
  "dev": true,
  "strict": false,
  "minify": false,
  "urlType": "exp"
}
```

Leaving it here because I wasn't able to find this in docs here or on expo website.

**Comment by dikaiosune** [comment]
@egor-laufer I don't think those commands would have had any effect -- CRNA runs the packager on port 19001, not 8081, and when xdl is in "offline" mode (which CRNA enables) the `lanType` is inferred to be `ip` anyways. No other lanType setting will have an effect in offline mode, IIRC.

Adding a docs label because network troubleshooting is likely to come up again, should be added to user guide.

**Comment by acomito** [comment]
I'm having a similar issue (same error code). I'm working out of a coworking space (a new one). I think they had a company come in and do a full setup (in terms of wifi, printer, etc) and I'm wondering if they used some security settings that are causing issues using expo. I had a similar wifi-related issue the other day trying to download a zip file. A lot of the other people here aren't developers, so it may not be something others run into.

Has anyone come across a similar situation?

**Comment by tingchaoxu** [comment]
Agree with @acomito. I have the same issue on my mac. I change to my iPhone hotspot 'npm run ios' and it works, so I change it back to my wifi and run it again and somehow it fixed and working again.
