### ISSUE TITLE
Hot Reloading is Enabled but no changes made

### ISSUE THREAD

**Issue by adhywiranata** [react-community/create-react-native-app#88]
When I saved my script, hot reload is enabled and the "Hot Loading..." tooltip shows up but no changes made. Also noticed that Bundling `node_modules/react-native-scripts/build/bin/crna-entry.js` is not logged when I did this. 

Hot reloading works perfectly with my other react-native projects (created using the react-native init), so currently assuming that this is an expo-related issue.

**Comment by dikaiosune** [comment]
Do you have both hot module replacement and live reloading enabled? CRNA apps have live reloading enabled by default, and turning on HMR will often break both for that packager session.

**Comment by adhywiranata** [comment]
Yeah, I saw the expo documentation said that Live Reload and Hot Module Reloading should not be both enabled. I tried disabling the HMR and enabling the Live Reload and it works just fine. But if I switched them (HMR enabled, Live Reload disabled), no changes are made.

What makes these strange is that somehow the HMR works when I intentionally break the app to show the error screen, but no changes when I change the app's component styles/states.

**Comment by kristojorg** [comment]
Also seeing this behavior in CRNA with live reloading disabled hot reloading enabled and a fresh packager session

**Comment by adhywiranata** [comment]
Thanks @kristojorg this solved my problem. Thanks!

**Comment by slorber** [comment]
Hi,

I'd like this to be reopened because I've made my first component a class and it does not solve the hot reload for nested components. imho. As long as you have one functional component in the tree it seems to prevent deeply nested classes to hot reload, which makes it barely unusable currently.

**Comment by samassango** [comment]
Hi 

I am experiencing this issue which is causing the app to crush


Bundling `node_modules\react-native-scripts\build\bin\crna-entry.js`
  No module changed.
I tried to reinstall the react-native-scripts but still no difference

**Comment by martianmartian** [comment]
still having this issue here. iphone 5.. can't even get through the tutorial because of this problem

**Comment by brentvatne** [comment]
@samassango @martianmartian - please try installing watchman: https://facebook.github.io/watchman/

**Comment by renatobenks** [comment]
@adhywiranata hey, your resolve fix it to me, but I'm still confusing about this, because before I didn't need a root component like class component, my root component was a normal functional component and the hot reloading was working very well, so after some changes don't works anymore, until now, with class component on root.

**Comment by exhesham** [comment]
Same issue here, however, I found some temporary workarounds to avoid wasting time on that. elaborated [here](https://exhesham.com/2017/12/06/overcoming-expo-xde-issues/)
